spring:
  application:
    name: devshowcase

  datasource:
    url: jdbc:postgresql://localhost:5433/devshowcase
    username: postgres
    password: 86065542

  jpa:
    hibernate:
      ddl-auto: update